env:
  global:
    secure: eOFZFo5W4wva/ZDI5j0HaIzXeSGQEuq7LILggX20NjZnNJFKt6iP8yj/NuhEutKrmwX42t5O4misilcKyyUmo/xheyiTMTTu8Qkx7A2HYxYOUmgvK0/vk1yyvUeW1iJYdLsUARACl5f8wjXafY1o0UCFjLlv078pmZsCmi2wYmQ=

language: node_js

branches:
  only: master

install:
  - npm install

script:
  - node ./_scripts/create-comment-issue.js

notifications:
  email:
    on_success: never
    on_failure: always